CREATE TABLE [Production].[Product_inmem] (
    [ProductID]             INT            IDENTITY (1, 1) NOT NULL,
    [Name]                  NVARCHAR (50)  NOT NULL,
    [ProductNumber]         NVARCHAR (25)  NOT NULL,
    [MakeFlag]              BIT            CONSTRAINT [IMDF_Product_MakeFlag] DEFAULT ((1)) NOT NULL,
    [FinishedGoodsFlag]     BIT            CONSTRAINT [IMDF_Product_FinishedGoodsFlag] DEFAULT ((1)) NOT NULL,
    [Color]                 NVARCHAR (15)  NULL,
    [SafetyStockLevel]      SMALLINT       NOT NULL,
    [ReorderPoint]          SMALLINT       NOT NULL,
    [StandardCost]          MONEY          NOT NULL,
    [ListPrice]             MONEY          NOT NULL,
    [Size]                  NVARCHAR (5)   NULL,
    [SizeUnitMeasureCode]   NCHAR (3)      NULL,
    [WeightUnitMeasureCode] NCHAR (3)      NULL,
    [Weight]                DECIMAL (8, 2) NULL,
    [DaysToManufacture]     INT            NOT NULL,
    [ProductLine]           NCHAR (2)      NULL,
    [Class]                 NCHAR (2)      NULL,
    [Style]                 NCHAR (2)      NULL,
    [ProductSubcategoryID]  INT            NULL,
    [ProductModelID]        INT            NULL,
    [SellStartDate]         DATETIME2 (7)  NOT NULL,
    [SellEndDate]           DATETIME2 (7)  NULL,
    [DiscontinuedDate]      DATETIME2 (7)  NULL,
    [ModifiedDate]          DATETIME2 (7)  CONSTRAINT [IMDF_Product_ModifiedDate] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [IMPK_Product_ProductID] PRIMARY KEY NONCLUSTERED HASH ([ProductID]) WITH (BUCKET_COUNT = 1048576),
    CONSTRAINT [IMCK_Product_Class] CHECK ([Class]='H' OR [Class]='h' OR [Class]='M' OR [Class]='m' OR [Class]='L' OR [Class]='l' OR [Class] IS NULL),
    CONSTRAINT [IMCK_Product_DaysToManufacture] CHECK ([DaysToManufacture]>=(0)),
    CONSTRAINT [IMCK_Product_ListPrice] CHECK ([ListPrice]>=(0.00)),
    CONSTRAINT [IMCK_Product_ProductLine] CHECK ([ProductLine]='R' OR [ProductLine]='r' OR [ProductLine]='M' OR [ProductLine]='m' OR [ProductLine]='T' OR [ProductLine]='t' OR [ProductLine]='S' OR [ProductLine]='s' OR [ProductLine] IS NULL),
    CONSTRAINT [IMCK_Product_ReorderPoint] CHECK ([ReorderPoint]>(0)),
    CONSTRAINT [IMCK_Product_SafetyStockLevel] CHECK ([SafetyStockLevel]>(0)),
    CONSTRAINT [IMCK_Product_SellEndDate] CHECK ([SellEndDate]>=[SellStartDate] OR [SellEndDate] IS NULL),
    CONSTRAINT [IMCK_Product_StandardCost] CHECK ([StandardCost]>=(0.00)),
    CONSTRAINT [IMCK_Product_Style] CHECK ([Style]='U' OR [Style]='u' OR [Style]='M' OR [Style]='m' OR [Style]='W' OR [Style]='w' OR [Style] IS NULL),
    CONSTRAINT [IMCK_Product_Weight] CHECK ([Weight]>(0.00)),
    INDEX [IX_ProductNumber] NONCLUSTERED ([ProductNumber]),
    INDEX [IX_Name] NONCLUSTERED ([Name])
)
WITH (MEMORY_OPTIMIZED = ON);

