CREATE TABLE [Sales].[SalesOrderHeader_inmem] (
    [SalesOrderID]           INT            IDENTITY (1, 1) NOT NULL,
    [RevisionNumber]         TINYINT        CONSTRAINT [IMDF_SalesOrderHeader_RevisionNumber] DEFAULT ((0)) NOT NULL,
    [OrderDate]              DATETIME2 (7)  NOT NULL,
    [DueDate]                DATETIME2 (7)  NOT NULL,
    [ShipDate]               DATETIME2 (7)  NULL,
    [Status]                 TINYINT        CONSTRAINT [IMDF_SalesOrderHeader_Status] DEFAULT ((1)) NOT NULL,
    [OnlineOrderFlag]        BIT            CONSTRAINT [IMDF_SalesOrderHeader_OnlineOrderFlag] DEFAULT ((1)) NOT NULL,
    [PurchaseOrderNumber]    NVARCHAR (25)  NULL,
    [AccountNumber]          NVARCHAR (15)  NULL,
    [CustomerID]             INT            NOT NULL,
    [SalesPersonID]          INT            CONSTRAINT [IMDF_SalesOrderHeader_SalesPersonID] DEFAULT ((-1)) NOT NULL,
    [TerritoryID]            INT            NULL,
    [BillToAddressID]        INT            NOT NULL,
    [ShipToAddressID]        INT            NOT NULL,
    [ShipMethodID]           INT            NOT NULL,
    [CreditCardID]           INT            NULL,
    [CreditCardApprovalCode] VARCHAR (15)   NULL,
    [CurrencyRateID]         INT            NULL,
    [SubTotal]               MONEY          CONSTRAINT [IMDF_SalesOrderHeader_SubTotal] DEFAULT ((0.00)) NOT NULL,
    [TaxAmt]                 MONEY          CONSTRAINT [IMDF_SalesOrderHeader_TaxAmt] DEFAULT ((0.00)) NOT NULL,
    [Freight]                MONEY          CONSTRAINT [IMDF_SalesOrderHeader_Freight] DEFAULT ((0.00)) NOT NULL,
    [Comment]                NVARCHAR (128) NULL,
    [ModifiedDate]           DATETIME2 (7)  NOT NULL,
    PRIMARY KEY NONCLUSTERED HASH ([SalesOrderID]) WITH (BUCKET_COUNT = 16777216),
    CONSTRAINT [IMCK_SalesOrderHeader_DueDate] CHECK ([DueDate]>=[OrderDate]),
    CONSTRAINT [IMCK_SalesOrderHeader_Freight] CHECK ([Freight]>=(0.00)),
    CONSTRAINT [IMCK_SalesOrderHeader_ShipDate] CHECK ([ShipDate]>=[OrderDate] OR [ShipDate] IS NULL),
    CONSTRAINT [IMCK_SalesOrderHeader_Status] CHECK ([Status]>=(0) AND [Status]<=(8)),
    CONSTRAINT [IMCK_SalesOrderHeader_SubTotal] CHECK ([SubTotal]>=(0.00)),
    CONSTRAINT [IMCK_SalesOrderHeader_TaxAmt] CHECK ([TaxAmt]>=(0.00)),
    INDEX [IX_CustomerID] NONCLUSTERED HASH ([CustomerID]) WITH (BUCKET_COUNT = 1048576),
    INDEX [IX_SalesPersonID] NONCLUSTERED HASH ([SalesPersonID]) WITH (BUCKET_COUNT = 1048576)
)
WITH (MEMORY_OPTIMIZED = ON);

